### ISSUE TITLE
Change logo on privly.org to the one without the dot. 

### ISSUE THREAD

**Issue by jewifer** [privly/privly-organization#23]
I have tried to change the logo, but have been unsuccessful. I used the documentation here: http://www.inmotionhosting.com/support/edu/drupal-7/customize-theme/upload-custom-logo and it did not work. I tried clearing the cache through the administrative interface and it still did not solve the issue. I found that Drupal Gardens had an issue with this, which may have been persistent to this page. 

At this point, I'm blocked. Not sure what else to try. 

This is the logo I'd like to use on the privly.org page: ![logo_large_bleed](https://f.cloud.github.com/assets/911251/2121197/2099324c-91d8-11e3-943f-9299a4bd4671.png)

**Comment by smcgregor** [comment]
Done!
