### ISSUE TITLE
Untrusted/Insecure Connection reported on some browsers

### ISSUE THREAD

**Issue by jatindhankhar** [privly/privly-organization#38]
When opening Privly site [priv.ly/](https://priv.ly/) many browsers give "Insecure / Untrusted connection warning". I guess some issue with certificate configuration on the Privly's side.

<hr>

Firefox 37.0.1 on Linux Mint 17.1 
![screenshot from 2015-04-14 19 33 31](https://cloud.githubusercontent.com/assets/2412081/7230382/d9de1890-e78a-11e4-86b5-2da6ce5fa2db.png)

<hr>

Chrome 42.0 on CM 12 (Lollipop 5.0.2)
![chrome_issue](https://cloud.githubusercontent.com/assets/2412081/7230451/bcc92c08-e78b-11e4-8c6f-d8eda7d7ec08.png)

<hr>

Firefox 37.0.2 on CM 12 (Lollipop 5.0.2)
![firefox_issue](https://cloud.githubusercontent.com/assets/2412081/7230438/9ca941ba-e78b-11e4-981f-92510889c7ef.png)

@smcgregor, please look into the issue

**Comment by smcgregor** [comment]
I believe we fixed this issue a while back. Are you still experiencing it?

**Comment by jatindhankhar** [comment]
Nope, looks like it's been fixed.
